tbn_maj_data_flush:
    pattern:  /{hash}/{subdomain}/flush
    defaults: { _controller: TBNMajDataBundle:Data:flush }
    requirements:
        subdomain: (\w+)
        hash: %secret%
        
tbn_maj_data_homepage:
    pattern:  /{hash}/{subdomain}/{site}
    defaults: { _controller: TBNMajDataBundle:Data:index, site: false }
    requirements:
        subdomain: (\w+)
        site:  bikini|soonight|dynamo|toulouse|facebook|tourisme
        hash: %secret%
