parameters:
    url_soonnight_tlse: http://www.soonnight.com/midi-pyrenees/sortir-midi-pyrenees,4.html?id_dept=15
    url_soonnight_paris: http://www.soonnight.com/paris/sortir-paris,4.html
    url_soonnight_marseille: http://www.soonnight.com/paca/sortir-paca,4.html?id_dept=40
    url_soonnight_lyon: http://www.soonnight.com/rhone-alpes/sortir-rhone-alpes,4.html?id_dept=21
    url_soonnight_brest: http://www.soonnight.com/bretagne/sortir-bretagne,4.html?id_dept=85
    url_soonnight_nantes: http://www.soonnight.com/pays-de-la-loire/sortir-pays-de-la-loire,4.html?id_dept=89
    url_soonnight_lille: http://www.soonnight.com/nord-pas-de-calais/sortir-nord-pas-de-calais,4.html?id_dept=32
    url_soonnight_montpellier: http://www.soonnight.com/languedoc-roussillon/sortir-languedoc-roussillon,4.html?id_dept=26
    url_soonnight_nice: http://www.soonnight.com/paca/sortir-paca,4.html?id_dept=11
    url_soonnight_bordeaux: http://www.soonnight.com/aquitaine/sortir-aquitaine,4.html?id_dept=36
    url_opendata_toulouse: https://data.toulouse-metropole.fr/explore/dataset/agenda-des-manifestations-culturelles-so-toulouse/download/?format=csv&timezone=Europe/Berlin&use_labels_for_header=true

services:
    tbn.event_updater:
        class: TBN\MajDataBundle\Updater\EventUpdater
        arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@tbn.social.facebook_admin"
          - "@tbn.event_handler"
    tbn.user_updater:
        class: TBN\MajDataBundle\Updater\UserUpdater
        arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@tbn.social.facebook_admin"
          - "@tbn.user_handler"
    tbn.event_fetcher:
        class: TBN\MajDataBundle\Fetcher\EventFetcher
        arguments:
          - "@tbn.parser_manager"
          - "@doctrine.orm.default_entity_manager"
    #Parsers
    tbn.parser.abstract:
        class: TBN\MajDataBundle\Parser\AgendaParser
    tbn.parser.abstracts.soonnight:
        class: TBN\MajDataBundle\Parser\Common\SoonNightParser
        calls:
            - ['addUrl', ["%url_soonnight_paris%"]]
            - ['addUrl', ["%url_soonnight_tlse%"]]
            - ['addUrl', ["%url_soonnight_marseille%"]]
            - ['addUrl', ["%url_soonnight_lyon%"]]
            - ['addUrl', ["%url_soonnight_brest%"]]
            - ['addUrl', ["%url_soonnight_nice%"]]
            - ['addUrl', ["%url_soonnight_nantes%"]]
            - ['addUrl', ["%url_soonnight_bordeaux%"]]
            - ['addUrl', ["%url_soonnight_lille%"]]
            - ['addUrl', ["%url_soonnight_montpellier%"]]

    tbn.parser.abstracts.facebook:
        class: TBN\MajDataBundle\Parser\Common\FaceBookParser
        arguments: ["@doctrine.orm.entity_manager", "@tbn.firewall", "@tbn.social.facebook_admin"]
    #Toulouse
    tbn.parser.toulouse.bikini:
        class: TBN\MajDataBundle\Parser\Toulouse\BikiniParser
    tbn.parser.toulouse.toulouse:
        class: TBN\MajDataBundle\Parser\Toulouse\ToulouseParser
        calls:
            - ['setUrl', ["%url_opendata_toulouse%"]]
    tbn.parser.toulouse.tourisme:
        class: TBN\MajDataBundle\Parser\Toulouse\ToulouseTourismeParser
    tbn.parser.toulouse.facebook:
        parent: tbn.parser.abstracts.facebook
    #Paris
    tbn.parser.paris.facebook:
        parent: tbn.parser.abstracts.facebook
    #Marseille
    tbn.parser.marseille.facebook:
        parent: tbn.parser.abstracts.facebook
    #lyon
    tbn.parser.lyon.facebook:
        parent: tbn.parser.abstracts.facebook
    #brest
    tbn.parser.brest.facebook:
        parent: tbn.parser.abstracts.facebook
    #nice
    tbn.parser.nice.facebook:
        parent: tbn.parser.abstracts.facebook
    #nantes
    tbn.parser.nantes.facebook:
        parent: tbn.parser.abstracts.facebook
    #bordeaux
    tbn.parser.bordeaux.facebook:
        parent: tbn.parser.abstracts.facebook
    #lille
    tbn.parser.lille.facebook:
        parent: tbn.parser.abstracts.facebook
    #montpellier
    tbn.parser.montpellier.facebook:
        parent: tbn.parser.abstracts.facebook

    #Alises
    tbn.facebook_parser:
        alias: tbn.parser.abstracts.facebook
    tbn.soonnight_parser:
        alias: tbn.parser.abstracts.soonnight
    tbn.toulouse_parser:
        alias: tbn.parser.toulouse.toulouse
    tbn.bikini_parser:
        alias: tbn.parser.toulouse.bikini
    tbn.toulouse_tourisme_parser:
        alias: tbn.parser.toulouse.tourisme

    #Manager
    tbn.parser_manager:
        class: TBN\MajDataBundle\Parser\Manager\ParserManager
        
    #Utils
    tbn.util:
        class: TBN\MajDataBundle\Utils\Util
    tbn.echantillon_handler:
        class: TBN\MajDataBundle\Handler\EchantillonHandler
        arguments: ["@doctrine.orm.entity_manager"]
    tbn.doctrine_event_handler:
        class: TBN\MajDataBundle\Handler\DoctrineEventHandler
        arguments: ["@doctrine.orm.entity_manager", "@tbn.event_handler", "@tbn.firewall", "@tbn.echantillon_handler"]
    tbn.event_handler:
        class: TBN\MajDataBundle\Handler\EventHandler
        arguments: ["@tbn.cleaner", "@tbn.comparator", "@tbn.merger", "%kernel.root_dir%/../web/uploads/temp"]
    tbn.user_handler:
        class: TBN\MajDataBundle\Handler\UserHandler
        arguments: ["%kernel.root_dir%/../web/uploads/temp"]
    tbn.comparator:
        class: TBN\MajDataBundle\Utils\Comparator
        arguments: ["@tbn.util", "@comparator_cache"]
    tbn.cleaner:
        class: TBN\MajDataBundle\Utils\Cleaner
        arguments: ["@tbn.util"]
    tbn.firewall:
        class: TBN\MajDataBundle\Utils\Firewall
        arguments: ["@doctrine", "@tbn.comparator"]
    tbn.merger:
        class: TBN\MajDataBundle\Utils\Merger
        arguments: ["@tbn.comparator"]

    #Cleaner
    tbn.image_cleaner:
        class: TBN\MajDataBundle\Cleaner\ImageCleaner
        arguments: ["@doctrine.orm.entity_manager", "@liip_imagine.cache.manager", "%kernel.root_dir%/../web"]
