parameters:
    url_soonnight_tlse: http://www.soonnight.com/midi-pyrenees/sortir-midi-pyrenees,4.html?id_dept=15
    url_soonnight_paris: http://www.soonnight.com/paris/sortir-paris,4.html
    url_soonnight_marseille: http://www.soonnight.com/paca/sortir-paca,4.html?id_dept=40
    url_soonnight_lyon: http://www.soonnight.com/rhone-alpes/sortir-rhone-alpes,4.html?id_dept=21
    url_soonnight_brest: http://www.soonnight.com/bretagne/sortir-bretagne,4.html?id_dept=85
    url_soonnight_nantes: http://www.soonnight.com/pays-de-la-loire/sortir-pays-de-la-loire,4.html?id_dept=89
    url_soonnight_lille: http://www.soonnight.com/nord-pas-de-calais/sortir-nord-pas-de-calais,4.html?id_dept=32
    url_soonnight_montpellier: http://www.soonnight.com/languedoc-roussillon/sortir-languedoc-roussillon,4.html?id_dept=26
    url_soonnight_nice: http://www.soonnight.com/paca/sortir-paca,4.html?id_dept=11
    url_soonnight_bordeaux: http://www.soonnight.com/aquitaine/sortir-aquitaine,4.html?id_dept=36
    url_opendata_toulouse: https://data.toulouse-metropole.fr/explore/dataset/agenda-des-manifestations-culturelles-so-toulouse/download/?format=csv&timezone=Europe/Berlin&use_labels_for_header=true

services:
    #Parsers
    tbn.parser.abstract:
        class: TBN\MajDataBundle\Parser\AgendaParser
    tbn.parser.abstracts.soonnight:
        class: TBN\MajDataBundle\Parser\Common\SoonNightParser
    tbn.parser.abstracts.facebook:
        class: TBN\MajDataBundle\Parser\Common\FaceBookParser
        arguments: ["@doctrine.orm.entity_manager", "@tbn.firewall", "@tbn.social.facebook_admin"]
    #Toulouse
    tbn.parser.toulouse.bikini:
        class: TBN\MajDataBundle\Parser\Toulouse\BikiniParser
    tbn.parser.toulouse.toulouse:
        class: TBN\MajDataBundle\Parser\Toulouse\ToulouseParser
        calls:
            - ['setUrl', ["%url_opendata_toulouse%"]]
    tbn.parser.toulouse.tourisme:
        class: TBN\MajDataBundle\Parser\Toulouse\ToulouseTourismeParser
    tbn.parser.toulouse.dynamo:
        class: TBN\MajDataBundle\Parser\Toulouse\DynamoParser
    tbn.parser.toulouse.soonnight:
        parent: tbn.parser.abstracts.soonnight
        calls:
            - ['setUrl', ["%url_soonnight_tlse%"]]
    tbn.parser.toulouse.facebook:
        parent: tbn.parser.abstracts.facebook
    #Paris
    tbn.parser.paris.tourisme:
        class: TBN\MajDataBundle\Parser\Paris\ParisTourismeParser
    tbn.parser.paris.soonnight:
        parent: tbn.parser.abstracts.soonnight
        calls:
            - ['setUrl', ["%url_soonnight_paris%"]]
    tbn.parser.paris.facebook:
        parent: tbn.parser.abstracts.facebook
    #Marseille
    tbn.parser.marseille.facebook:
        parent: tbn.parser.abstracts.facebook
    tbn.parser.marseille.soonnight:
      parent: tbn.parser.abstracts.soonnight
      calls:
        - ['setUrl', ["%url_soonnight_marseille%"]]
    #lyon
    tbn.parser.lyon.facebook:
        parent: tbn.parser.abstracts.facebook
    tbn.parser.lyon.soonnight:
      parent: tbn.parser.abstracts.soonnight
      calls:
        - ['setUrl', ["%url_soonnight_lyon%"]]
    #brest
    tbn.parser.brest.facebook:
        parent: tbn.parser.abstracts.facebook
    tbn.parser.brest.soonnight:
      parent: tbn.parser.abstracts.soonnight
      calls:
        - ['setUrl', ["%url_soonnight_brest%"]]
    #nice
    tbn.parser.nice.facebook:
        parent: tbn.parser.abstracts.facebook
    tbn.parser.nice.soonnight:
      parent: tbn.parser.abstracts.soonnight
      calls:
            - ['setUrl', ["%url_soonnight_nice%"]]
    #nantes
    tbn.parser.nantes.facebook:
        parent: tbn.parser.abstracts.facebook
    tbn.parser.nantes.soonnight:
      parent: tbn.parser.abstracts.soonnight
      calls:
        - ['setUrl', ["%url_soonnight_nantes%"]]
    #bordeaux
    tbn.parser.bordeaux.facebook:
        parent: tbn.parser.abstracts.facebook
    tbn.parser.bordeaux.soonnight:
      parent: tbn.parser.abstracts.soonnight
      calls:
        - ['setUrl', ["%url_soonnight_bordeaux%"]]
    #lille
    tbn.parser.lille.facebook:
        parent: tbn.parser.abstracts.facebook
    tbn.parser.lille.soonnight:
      parent: tbn.parser.abstracts.soonnight
      calls:
        - ['setUrl', ["%url_soonnight_lille%"]]
    #montpellier
    tbn.parser.montpellier.facebook:
        parent: tbn.parser.abstracts.facebook
    tbn.parser.montpellier.soonnight:
      parent: tbn.parser.abstracts.soonnight
      calls:
        - ['setUrl', ["%url_soonnight_montpellier%"]]
        
    #Manager
    parser_manager:
        class: TBN\MajDataBundle\Parser\Manager\ParserManager
        
    #Utils
    tbn.util:
        class: TBN\MajDataBundle\Utils\Util
    tbn.doctrine_event_handler:
        class: TBN\MajDataBundle\Utils\DoctrineEventHandler
        arguments: ["@doctrine.orm.entity_manager", "@tbn.event_handler", "@tbn.firewall", "@tbn.social.facebook_admin", "@memory_cache"]
    tbn.event_handler:
        class: TBN\MajDataBundle\Utils\EventHandler
        arguments: ["@tbn.firewall", "@tbn.cleaner", "@tbn.comparator", "@tbn.merger", "%kernel.root_dir%/../web/uploads/temp"]
    tbn.comparator:
        class: TBN\MajDataBundle\Utils\Comparator
        arguments: ["@tbn.util", "@array_cache"]
    tbn.cleaner:
        class: TBN\MajDataBundle\Utils\Cleaner
        arguments: ["@tbn.util"]
    tbn.firewall:
        class: TBN\MajDataBundle\Utils\Firewall
        arguments: ["@doctrine", "@tbn.comparator"]
    tbn.merger:
        class: TBN\MajDataBundle\Utils\Merger
        arguments: ["@tbn.comparator"]

    #Cleaner
    tbn.image_cleaner:
        class: TBN\MajDataBundle\Cleaner\ImageCleaner
        arguments: ["@doctrine.orm.entity_manager", "@liip_imagine.cache.manager", "@filesystem", "%kernel.root_dir%/../web"]
