parameters:
    application_version: '2.0.0'
    facebook_id_page: '205292952998805'
    facebook_id_app: '%env(FACEBOOK_API_ID)%'
    google_map_key: '%env(GOOGLE_MAP_KEY_WEB)%'
    twitter_id_page: 'By__Night'
    app_public_root: '%kernel.project_dir%/public/'
    class.guzzle.response: Guzzle\Http\Message\Response
    class.guzzle.client: Guzzle\Http\Client
    class.guzzle.oauthplugin: Guzzle\Plugin\Oauth\OauthPlugin
    twitter.baseurl: https://api.twitter.com/1.1
    url_opendata_toulouse: https://data.toulouse-metropole.fr/explore/dataset/agenda-des-manifestations-culturelles-so-toulouse/download/?format=csv&timezone=Europe/Berlin&use_labels_for_header=true
