framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: "redis://%env(REDIS_HOST)%"
        pools:
            redis.app_cache_pool:
                adapter: cache.app
            redis.datatourisme_cache_pool:
                adapter: cache.adapter.array
