doctrine_cache:
    custom_providers:
        location:
            prototype: 'App\Cache\LocationCacheProvider'
    providers:
        redis:
            type: redis
            redis:
                host: '%env(REDIS_HOST)%'
                port: '%env(REDIS_PORT)%'
            namespace: memory_ns
            aliases:
                - redis_cache
                - memory_cache
        location:
            name: location_cache
            location: ~
            namespace: location_ns
            aliases:
                - location_cache
        array:
            type: array
            namespace: array_ns
            aliases:
                - array_cache