doctrine_cache:
    providers:
        redis:
            type: redis
            redis:
                host: '%env(REDIS_HOST)%'
                port: '%env(REDIS_PORT)%'
            namespace: memory_ns
            aliases:
                - redis_cache
                - memory_cache
        array:
            type: array
            namespace: array_ns
            aliases:
                - array_cache
