doctrine_cache:
    custom_providers:
        location:
            prototype: 'App\Cache\LocationCacheProvider'
    providers:
        redis:
            type: redis
            redis:
                host: '%env(REDIS_HOST)%'
                port: '%env(REDIS_PORT)%'
            namespace: memory_cache_ns
            aliases:
                - memory_cache
        location_cache:
            name: location_cache
            location: ~
            namespace: location_cache_ns
        array:
            type: array
            namespace: array_cache_ns
            aliases:
                - array_cache
        comparator:
            type: array
            namespace: comparator_cache_ns
            aliases:
                - comparator_cache
        