easy_admin:
    site_name: 'By Night Administration'
    design:
        menu:
            - { label: 'Back to Home', url: '../', target: '_blank', icon: 'home'  }
            - { label: 'Commnunity' }
            - { label: 'Events', entity: Event, params: { action: 'list' }, icon: 'calendar' }
            - { label: 'Places', entity: Place, params: { action: 'list' }, icon: 'map-marker-alt' }
            - { label: 'Comments', entity: Comment, params: { action: 'list' }, icon: 'comment' }
            - { label: 'Calendriers', entity: Calendrier, params: { action: 'list' }, icon: 'calendar-alt' }
            - { label: 'Users' }
            - { label: 'Users', entity: User, params: { action: 'list' }, icon: 'users' }
            - { label: 'User socials', entity: UserInfo, params: { action: 'list' }, icon: 'bullhorn' }
            - { label: 'Administration' }
            - { label: 'Countries', entity: Country, params: { action: 'list' }, icon: 'globe-europe' }
            - { label: 'Site socials', entity: SiteInfo, params: { action: 'list' }, icon: 'bullhorn' }
            - { label: 'Explorations', entity: Exploration, params: { action: 'list' }, icon: 'eye' }
            - { label: 'Historique Maj', entity: HistoriqueMaj, params: { action: 'list' }, icon: 'history' }

    entities:
        Event:
            class: App\Entity\Event
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'createdAt' }
                    - { property: 'updatedAt' }
                    - { property: 'fromData' }
                    - { property: 'nom' }
                    - { property: 'place' }
            form:
                fields:
                    - { type: 'group', columns: 8, label: 'Informations' }
                    - { property: 'id', type_options: { disabled: true } }
                    - { property: 'user', type: 'easyadmin_autocomplete' }
                    - { property: 'createdAt' }
                    - { property: 'updatedAt' }
                    - { property: 'externalId' }
                    - { property: 'slug' }
                    - { property: 'nom' }
                    - { property: 'dateDebut' }
                    - { property: 'dateFin' }
                    - { property: 'horaires' }
                    - { property: 'descriptif' }
                    - { property: 'externalUpdatedAt' }
                    - { property: 'modificationDerniereMinute' }
                    - { property: 'typeManifestation' }
                    - { property: 'categorieManifestation' }
                    - { property: 'themeManifestation' }
                    - { property: 'reservationTelephone' }
                    - { property: 'reservationEmail' }
                    - { property: 'reservationInternet' }
                    - { property: 'tarif' }
                    - { property: 'brouillon' }
                    - { property: 'archive' }
                    - { type: 'group', columns: 4, label: 'Lieu' }
                    - { property: 'place', type: 'easyadmin_autocomplete' }
                    - { property: 'placeName' }
                    - { property: 'placeStreet' }
                    - { property: 'placeCity' }
                    - { property: 'placePostalCode' }
                    - { property: 'placeExternalId' }
                    - { property: 'placeFacebookId' }
                    - { property: 'placeCountry' }
                    - { property: 'latitude' }
                    - { property: 'longitude' }
                    - { property: 'adresse' }
                    - { type: 'group', columns: 8, label: 'Images' }
                    - { property: 'url' }
                    - { property: 'image.name'}
                    - { property: 'imageSystem.name'}
                    - { type: 'group', columns: 4, label: 'Parser' }
                    - { property: 'fromData' }
                    - { property: 'parserVersion' }
                    - { property: 'source' }
        User:
            class: App\Entity\User
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'username' }
                    - { property: 'email' }
                    - { property: 'lastLogin' }
            form:
                fields:
                    - { type: 'group', columns: 8, label: 'Informations' }
                    - { property: 'id', type_options: { disabled: true } }
                    - { property: 'slug' }
                    - { property: 'username' }
                    - { property: 'roles' }
                    - { property: 'email' }
                    - { property: 'firstname' }
                    - { property: 'lastname' }
                    - { property: 'description' }
                    - { property: 'info' }
                    - { property: 'from_login' }
                    - { property: 'show_socials' }
                    - { property: 'website' }
                    - { property: 'lastLogin' }
                    - { type: 'group', columns: 4, label: 'Médias' }
                    - { property: 'image.name' }
                    - { property: 'imageSystem.name' }
        Place:
            class: App\Entity\Place
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'nom' }
                    - { property: 'city' }
                    - { property: 'country' }
            form:
                fields:
                    - { type: 'group', columns: 8, label: 'Informations' }
                    - { property: 'id', type_options: { disabled: true } }
                    - { property: 'externalId' }
                    - { property: 'slug' }
                    - { property: 'nom' }
                    - { property: 'facebookId' }
                    - { property: 'junk' }
                    - { type: 'group', columns: 4, label: 'Lieu' }
                    - { property: 'rue' }
                    - { property: 'codePostal' }
                    - { property: 'ville' }
                    - { property: 'latitude' }
                    - { property: 'longitude' }
                    - { property: 'city', type: 'easyadmin_autocomplete' }
                    - { property: 'country' }
        Calendrier:
            class: App\Entity\Calendrier
            list:
                fields:
                    - { property: 'id', type_options: { disabled: true } }
                    - { property: 'updatedAt' }
                    - { property: 'event' }
                    - { property: 'user' }
                    - { property: 'participe' }
                    - { property: 'interet' }
            form:
                fields:
                    - { property: 'id', type_options: { disabled: true } }
                    - { property: 'updatedAt' }
                    - { property: 'event', type: 'easyadmin_autocomplete' }
                    - { property: 'user', type: 'easyadmin_autocomplete' }
                    - { property: 'participe' }
                    - { property: 'interet' }
        Comment:
            class: App\Entity\Comment
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'createdAt' }
                    - { property: 'event' }
                    - { property: 'user' }
                    - { property: 'approuve' }
            form:
                fields:
                    - { property: 'id', type_options: { disabled: true } }
                    - { property: 'event', type: 'easyadmin_autocomplete' }
                    - { property: 'user', type: 'easyadmin_autocomplete' }
                    - { property: 'createdAt' }
                    - { property: 'updatedAt' }
                    - { property: 'approuve' }
                    - { property: 'commentaire' }
        Exploration:
            class: App\Entity\Exploration
        HistoriqueMaj:
            class: App\Entity\HistoriqueMaj
        SiteInfo:
            class: App\Entity\SiteInfo
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'facebookId' }
                    - { property: 'googleId' }
                    - { property: 'twitterId' }
        UserInfo:
            class: App\Entity\UserInfo
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'facebookId' }
                    - { property: 'googleId' }
                    - { property: 'twitterId' }

        City:
            class: App\Entity\City

        Country:
            class: App\Entity\Country
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'displayName' }
            form:
                fields:
                    - { property: 'id', type_options: { disabled: true } }
                    - { property: 'locale' }
                    - { property: 'name' }
                    - { property: 'displayName' }
                    - { property: 'atDisplayName' }
                    - { property: 'capital' }
                    - { property: 'postalCodeRegex' }
