#HTTP Cache
fos_http_cache:
    tags:
        enabled: true

    proxy_client:
        varnish:
            http:
                servers:
                    - varnish
                base_url: '%env(APP_URL)%'
