fos_user:
    db_driver: orm
    firewall_name: main  
    user_class: App\Entity\User
    from_email:
        address: "support@by-night.fr"
        sender_name: "By Night"
    profile:
        form:
            type: App\Form\Type\ProfileFormType
    registration:
        form:
            type: App\Form\Type\RegistrationFormType
