framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    #csrf_protection: ~
    #http_method_override: true

    templating:
        engines: ['twig']

    session:
        handler_id: 'session.handler.native_file'
        cookie_secure: auto
        cookie_samesite: lax
        save_path: "%kernel.project_dir%/var/sessions/%kernel.environment%"

    assets:
        base_urls: '%env(APP_ASSET_URL)%'
        packages:
            local:
            cdn:
                base_urls: "%env(AWS_S3_URL)%"

    esi: true
    fragments: ~
    php_errors:
        log: true
