framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    #csrf_protection: ~
    #http_method_override: true

    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax

    esi: true
    fragments: ~
    php_errors:
        log: true
