hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the 
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: App\Security\Core\User\FOSUBUserProvider
        confirmation: false

    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
            google:   google_id
            twitter:  twitter_id

    resource_owners:
        twitter:
            type:               twitter
            client_id:          '%env(TWITTER_API_ID)%'
            client_secret:      '%env(TWITTER_API_SECRET)%'
            options:
                include_email: true
        facebook_admin:
            type:                facebook
            client_id:           '%env(FACEBOOK_API_ID)%'
            client_secret:       '%env(FACEBOOK_API_SECRET)%'
            scope:               email, pages_show_list, manage_pages
            infos_url:           https://graph.facebook.com/v3.3/me?fields=name,email,picture.type(large)
            paths:
                email:          email
                profilepicture: picture.data.url
        facebook_list_events:
            type:                facebook
            client_id:           '%env(FACEBOOK_API_ID)%'
            client_secret:       '%env(FACEBOOK_API_SECRET)%'
            scope:               email, user_events
            infos_url:           https://graph.facebook.com/v3.3/me?fields=name,email,picture.type(large)
            paths:
                email:          email
                profilepicture: picture.data.url
        facebook:
            type:                facebook
            client_id:           '%env(FACEBOOK_API_ID)%'
            client_secret:       '%env(FACEBOOK_API_SECRET)%'
            scope:               email
            infos_url:           https://graph.facebook.com/v3.3/me?fields=name,email,picture.type(large)
            paths:
                email:          email
                profilepicture: picture.data.url
        google:
            type:                google
            client_id:           '%env(GOOGLE_API_ID)%'
            client_secret:       '%env(GOOGLE_API_SECRET)%'
            scope:               "email profile"
