security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|bundles|thumb|thumb-asset|media|uploads)/
            security: false

        main:
            anonymous: true
            pattern: ^/

            guard:
                authenticators:
                    - App\Security\UserSocialAuthenticator
            form_login:
                provider: fos_userbundle
                #csrf_token_generator: security.csrf.token_manager
                use_referer: true
                default_target_path: app_main_index
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                success_handler: App\Handler\AuthenticationHandler
                failure_handler: App\Handler\AuthenticationHandler

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

            logout:
                delete_cookies: ['PHPSESSID']

    access_control:
        - { path: ^/login-social/service/eventbrite, roles: ROLE_ADMIN }
        - { path: ^/_administration, roles: ROLE_ADMIN }
        - { path: ^/social, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/espace-perso, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login-social, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_private, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1, 192.168.0.1/24] }
