security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|img|js|prod)/
            security: false

        main:
            pattern: ^/
            anonymous:    true

            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
                success_handler: App\Handler\AuthenticationHandler
                failure_handler: App\Handler\AuthenticationHandler

            oauth:
                remember_me: true
                resource_owners:
                    facebook_admin:    "/login-social/check-facebook-admin"
                    facebook_list_events:    "/login-social/check-facebook-list-events"
                    facebook:           "/login-social/check-facebook"
                    google:             "/login-social/check-google"
                    twitter:            "/login-social/check-twitter"
                login_path:        /login
                failure_path:      /login

                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: App\Security\Core\User\FOSUBUserProvider
            logout:
                invalidate_session:   true

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        - { path: ^/espace-perso, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/commentaire, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/social, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_administration, role: ROLE_ADMIN }
        - { path: ^/_private, roles: [IS_AUTHENTICATED_ANONYMOUSLY], ips: [127.0.0.1] }
