security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|bundles|media|prod|uploads)/
            security: false

        main:
            anonymous: true
            pattern: ^/

            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                use_referer: true
                default_target_path: app_main_index
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                success_handler: App\Handler\AuthenticationHandler
                failure_handler: App\Handler\AuthenticationHandler

            oauth:
                remember_me: true
                resource_owners:
                    facebook_admin: "/login-social/check-facebook-admin"
                    facebook_list_events: "/login-social/check-facebook-list-events"
                    facebook: "/login-social/check-facebook"
                    google: "/login-social/check-google"
                    twitter: "/login-social/check-twitter"
                login_path: fos_user_security_login
                failure_path: fos_user_security_login

                oauth_user_provider:
                    service: App\Security\Core\User\FOSUBUserProvider

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

            logout: true

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/espace-perso, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/commentaire, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/social, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/_administration, roles: ROLE_ADMIN }
        - { path: ^/_private, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1, 192.168.0.1/24] }
