sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: false
    monolog:
        error_handler:
            enabled: true
            level: error
    options:
        environment: '%kernel.environment%'
        release: '%env(APP_VERSION)%' #your app version
