php_version: 7.2

pre_composer_script: |
    #!/bin/bash

    pecl install redis

php_ini: |
    extension=redis.so

rules:
    php.duplicated_code:
        enabled: false
    doctrine.use_flush_in_loop:
        enabled: false
    symfony.controller.action_method_too_long:
        enabled: false
    symfony.controller.too_many_template_variables:
        enabled: true
        max_count: 10
        threshold: 5
