version: '3.4'

services:
    app:
        build: ./docker/dev
        environment:
            - BLACKFIRE_CLIENT_ID
            - BLACKFIRE_CLIENT_TOKEN
        depends_on:
            - elasticsearch
            - rabbitmq
            - redis
        volumes:
            - nfsmount:/app
        ports:
            - 8000:80

    worker:
        build: ./docker/dev
        container_name: worker
        command: ["worker"]
        depends_on:
            - elasticsearch
            - rabbitmq
            - redis
            - app
        volumes:
            - nfsmount:/app

    assets:
        image: nginx:1.17
        ports:
            - 8002:80
        volumes:
            - ./public:/assets:ro
            - ./docker/dev/assets/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app

    varnish:
        image: varnish:6.0
        command: ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-t" , "0"]
        ports:
            - 8001:80
        depends_on:
            - app
        volumes:
            - ./docker/dev/varnish/default.vcl:/etc/varnish/default.vcl:ro
            - ./docker/dev/varnish/fos:/etc/varnish/fos:ro
            - /usr/local/var/varnish

    redis:
        image: redis:alpine

    rabbitmq:
        image: rabbitmq:3.8-management
        ports:
            - 15672:15672
        volumes:
            - /var/lib/rabbitmq

    blackfire:
        image: blackfire/blackfire
        environment:
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.5
        environment:
            - node.name=es01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        volumes:
            - esdata:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:6.8.5
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch

volumes:
    nfsmount:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":/System/Volumes/Data/${PWD}"
    esdata:
