version: '3.2'

services:
  redis-manager:
    image: marian/rebrow:latest
    ports:
    - 5001:5001
    depends_on:
    - redis
    networks:
    - backend
  app:
    volumes:
    - ${SYMFONY_APP_PATH}:/var/www/symfony:cached