version: '3.2'

services:
    app:
        build: ${DOCKER_PATH}/php-nginx
        ports:
            - 8000:80
        links:
            - elk:elasticsearch
        environment:
            - BLACKFIRE_CLIENT_ID
            - BLACKFIRE_CLIENT_TOKEN
        depends_on:
            - elk
            - redis
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:cached

    varnish:
        image: million12/varnish
        ports:
            - 8001:80
        depends_on:
            - app
        volumes:
            - ${DOCKER_PATH}/varnish/default.vcl:/etc/varnish/default.vcl
            - /var/lib/varnish

    redis:
        image: redis:alpine

    rabbitmq:
        image: rabbitmq:3.7-management
        ports:
            - 15672:15672
        volumes:
            - /var/lib/rabbitmq

    blackfire:
        image: blackfire/blackfire
        environment:
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN

    elk:
        image: sebp/elk:661
        environment:
            - ES_JAVA_OPTS
        ports:
            - 5601:5601
            - 9200:9200
        volumes:
            - /var/lib/elasticsearch
