version: '2'

services:
    db:
        image: mysql:latest
        volumes:
            - db-data:/var/lib/mysql
            - ${DOCKER_PATH}/mysql/app.cnf:/etc/mysql/conf.d/app.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
        networks:
            - backend
    redis:
        image: redis:alpine
        restart: always
        networks:
            - backend
    # node:
    #     image: node:6
    #     restart: always
    #     volumes_from:
    #         - php
    #     networks:
    #         - backend
    rabbitmq:
        image: rabbitmq:latest
        restart: always
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - db
        ports:
            - 8001:80
        volumes:
            - ${DOCKER_PATH}/phpmyadmin/nginx.conf:/etc/nginx/conf.d/overrides.conf
            - ${DOCKER_PATH}/phpmyadmin/php.conf:/etc/php7/conf.d/99-overrides.conf
        networks:
            - backend
        restart: always
    php:
        build: ${DOCKER_PATH}/php-fpm
        links:
            - elk:elasticsearch
        depends_on:
            - db
        volumes:
             - ${SYMFONY_APP_PATH}:/var/www/symfony
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
        networks:
            - backend
    nginx:
        build: ${DOCKER_PATH}/nginx
        ports:
            - 8000:80
        links:
            - php
            - elk
        volumes_from:
            - php
        depends_on:
            - db
            - elk
            - php
            - redis
        volumes:
            - ${SYMFONY_APP_PATH}/var/logs/nginx/:/var/log/nginx
        restart: always
        networks:
            - frontend
            - backend
    blackfire:
        image: blackfire/blackfire
        environment:
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
        networks:
            - backend
        restart: always
    elk:
        image: sebp/elk:latest
        ports:
            - 5602:5601
            - 9201:9200
            - 9301:9300
            - 5045:5044
        volumes:
            - ${SYMFONY_APP_PATH}/var/logs:/var/www/symfony/var/logs
            - ${SYMFONY_APP_PATH}/var/logs/nginx:/var/log/nginx
            - elk-data:/var/lib/elasticsearch
        networks:
            - backend
            - frontend
        restart: always
volumes:
    db-data:
        driver: local
    elk-data:
        driver: local

networks:
    frontend:
    backend:
