version: '3.4'

services:
    assets:
        image: nginx:1.17-alpine
        ports:
            - 8002:80
        volumes:
            - ./public:/assets:ro
            - ./docker/dev/assets/nginx.conf:/etc/nginx/nginx.conf:ro

    varnish:
        image: varnish:6.0
        command: ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-t" , "0"]
        ports:
            - 8001:80
        volumes:
            - ./docker/dev/varnish/default.vcl:/etc/varnish/default.vcl:ro
            - ./docker/dev/varnish/fos:/etc/varnish/fos:ro
        tmpfs:
            - /usr/local/var/varnish
    redis:
        image: redis:alpine
        ports:
            - 6379:6379

    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        hostname: 'mabbit'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq:/var/lib/rabbitmq

    blackfire:
        image: blackfire/blackfire
        environment:
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.5
        environment:
            - node.name=es01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        volumes:
            - esdata:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:6.8.5
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch

volumes:
    esdata:
    rabbitmq:
