version: '2'

services:
    db:
        image: mysql:latest
        volumes:
            - db-data:/var/lib/mysql
            - ${DOCKER_PATH}/mysql/app.cnf:/etc/mysql/conf.d/app.cnf
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        restart: always
        networks:
            - backend
    redis:
        image: redis:alpine
        restart: always
        networks:
            - backend
#    node:
#        build: ${DOCKER_PATH}/node
#        volumes:
#            - ${SYMFONY_APP_PATH}/front:/app/front
#            - ${SYMFONY_APP_PATH}/web/prod:/app/dist
    rabbitmq:
        image: rabbitmq:management
        ports:
            - 15672:15672
        volumes:
            - queue-data:/var/lib/rabbitmq
        restart: always
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - db
        ports:
            - 8001:80
        volumes:
            - ${DOCKER_PATH}/phpmyadmin/nginx.conf:/etc/nginx/conf.d/overrides.conf
            - ${DOCKER_PATH}/phpmyadmin/php.conf:/etc/php7/conf.d/99-overrides.conf
        networks:
            - backend
        restart: always
    php:
        build: ${DOCKER_PATH}/php-fpm
        links:
            - elk:elasticsearch
        depends_on:
            - db
        volumes:
             - ${SYMFONY_APP_PATH}:/var/www/symfony
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - APP_ENV
            - APP_DEBUG
            - SYMFONY_ALLOW_APPDEV
        restart: always
        networks:
            - backend
    nginx:
        build: ${DOCKER_PATH}/nginx
        ports:
            - 8000:80
        volumes_from:
            - php
        depends_on:
            - db
            - elk
            - php
            - redis
        volumes:
            - ${SYMFONY_APP_PATH}/var/logs/nginx/:/var/log/nginx
        restart: always
        networks:
            - frontend
            - backend
    varnish:
        image: million12/varnish
        ports:
            - 8080:80
        depends_on:
            - nginx
        environment:
            CACHE_SIZE: "1G"
        volumes:
          - ${DOCKER_PATH}/varnish/default.vcl:/etc/varnish/default.vcl
          - varnish-data:/var/lib/varnish
        restart: always
        networks:
            - frontend
            - backend
    blackfire:
        image: blackfire/blackfire
        environment:
            - BLACKFIRE_CLIENT_ID
            - BLACKFIRE_CLIENT_TOKEN
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN
        networks:
            - backend
    elk:
        image: sebp/elk:latest
        ports:
            - 5601:5601
            - 9200:9200
        volumes:
            - ${SYMFONY_APP_PATH}/var/logs:/var/www/symfony/var/logs
            - ${SYMFONY_APP_PATH}/var/logs/nginx:/var/log/nginx
            - elk-data:/var/lib/elasticsearch
        networks:
            - backend
            - frontend
        restart: always
volumes:
    db-data:
        driver: local
    elk-data:
        driver: local
    queue-data:
        driver: local
    varnish-data:
        driver: local

networks:
    frontend:
    backend:
