version: '3.4'

x-defaults: &defaults
    build: ./docker/dev
    environment:
        - BLACKFIRE_CLIENT_ID
        - BLACKFIRE_CLIENT_TOKEN
    depends_on:
        - elasticsearch
        - rabbitmq
        - redis
    volumes:
        - .:/app:cached
        - ./var:/app/var:delegated

services:
    app:
        <<: *defaults
        ports:
            - 8000:80

    worker:
        <<: *defaults
        depends_on:
            - app
        command: worker

    assets:
        image: nginx:1.17
        ports:
            - 8002:80
        volumes:
            - ./public:/assets:ro
            - ./docker/dev/assets/nginx.conf:/etc/nginx/nginx.conf:ro

    varnish:
        image: million12/varnish
        ports:
            - 8001:80
        depends_on:
            - app
        environment:
            - "VARNISHD_PARAMS=-t 0"
        volumes:
            - ./docker/dev/varnish/default.vcl:/etc/varnish/default.vcl
            - ./docker/dev/varnish/fos:/etc/varnish/fos
            - /var/lib/varnish

    redis:
        image: redis:alpine

    rabbitmq:
        image: rabbitmq:3.7-management
        ports:
            - 15672:15672
        volumes:
            - /var/lib/rabbitmq

    blackfire:
        image: blackfire/blackfire
        environment:
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN

    elasticsearch:
        image: elasticsearch:6.7.1
        environment:
            - node.name=es01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        volumes:
            - /usr/share/elasticsearch/data

    kibana:
        image: kibana:6.7.1
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
