#tbn_user_post_search:
#    path: /requete
#    defaults: { _controller: TBNUserBundle:User:searchRedirect }
#    requirements:
#        method: POST
#
#tbn_user_search:
#    path: /recherche/{term}
#    defaults: { _controller: TBNUserBundle:User:search, term: null }
#    requirements:
#        method: GET

tbn_user_search:
    path: /recherche/{term}
    defaults: { _controller: TBNUserBundle:User:urlRedirect, term: null }

tbn_user_list:
    path: /
    defaults: { _controller: TBNUserBundle:User:urlRedirect, term: null }

tbn_user_stats:
    path: /{username}.html/stats/{type}
    defaults: { _controller: TBNUserBundle:User:stats }
    requirements:
        type: (semaine|mois|annee)
        username: (.+)

tbn_user_details:
    path: /{username}.html
    defaults: { _controller: TBNUserBundle:User:details }
    requirements:
        username: ([^/]+)
