tbn_user_participer:
    path: /participer/{id}
    defaults: { _controller: TBNAgendaBundle:Calendrier:participer, participer: true, interet: false }
    requirements:
        method: POST
        id: (\d+)
    
tbn_user_interesser:
    path: /interesser/{id}
    defaults: { _controller: TBNAgendaBundle:Calendrier:participer, participer: false, interet: true }
    requirements:
        method: POST
        id: (\d+)

tbn_agenda_new:
    path: /nouvelle-soiree
    defaults: { _controller: TBNUserBundle:Agenda:new }

tbn_agenda_delete:
    path: /supprimer/{id}
    defaults: { _controller: TBNUserBundle:Agenda:delete }
    requirements:
        method: _DELETE
        id: (\d+)
        
tbn_agenda_edit:
    path: /corriger/{slug}
    defaults: { _controller: TBNUserBundle:Agenda:edit }
    
tbn_agenda_brouillon:
    path: /brouillon/{slug}
    defaults: { _controller: TBNUserBundle:Agenda:brouillon }
    
tbn_agenda_annuler:
    path: /annuler/{slug}
    defaults: { _controller: TBNUserBundle:Agenda:annuler }

tbn_agenda_list:
    path: /mes-soirees
    defaults: { _controller: TBNUserBundle:Agenda:list }
