tbn_user_search:
    path: /recherche/{term}
    defaults: { _controller: TBNUserBundle:User:urlRedirect, term: null }

tbn_user_list:
    path: /
    defaults: { _controller: TBNUserBundle:User:urlRedirect, term: null }

tbn_user_stats:
    path: /{slug}--{id}.html/stats/{type}
    defaults: { _controller: TBNUserBundle:User:stats }
    requirements:
        type: (semaine|mois|annee)
        slug: (.+)
        id: (\d+)

tbn_user_details:
    path: /{slug}--{id}.html
    defaults: { _controller: TBNUserBundle:User:details }
    requirements:
        slug: (.+)
        id: (\d+)

