parameters:
    my_user_provider.class: TBN\UserBundle\Security\Core\User\FOSUBUserProvider
    class.guzzle.response: Guzzle\Http\Message\Response
    class.guzzle.client: Guzzle\Http\Client
    class.guzzle.oauthplugin: Guzzle\Plugin\Oauth\OauthPlugin
    twitter.baseurl: https://api.twitter.com/1.1
    twitter.config:
    consumer_key: "%twitter_app_id%"
    consumer_secret: "%twitter_app_secret%"
 
services:
    tbn.captcha_listener:
        class: TBN\UserBundle\EventListener\ReCaptchaListener
        arguments: ["fos_user_registration_form", "recaptcha"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: "onKernelController" }

    tbn.captcha_wrapper:
        class: TBN\UserBundle\Captcha\CaptchaWrapper
        arguments: ["@request_stack", "%google_recaptcha_secret%"]

    tbn.validation.response_validator:
        class: TBN\UserBundle\Validator\Constraints\ReCaptchaResponseValidator
        arguments: ["@tbn.captcha_wrapper"]
        tags:
          - { name: validator.constraint_validator, alias: recaptcha_response_validator }

    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ["@fos_user.user_manager", {facebook: facebook_id, google: google_id, twitter: twitter_id}, "@site_manager", "@doctrine", {google: "@tbn.social.google", twitter: "@tbn.social.twitter", facebook_events: "@tbn.social.facebook_events", facebook_admin: "@tbn.social.facebook_admin", facebook_list_events: "@tbn.social.facebook_list_events", facebook: "@tbn.social.facebook"}]

    tbn.registration.form.type:
        class: TBN\UserBundle\Form\Type\RegistrationFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: tbn_user_registration }

    tbn.form.type.recaptcha:
            class: TBN\UserBundle\Form\Type\ReCaptchaType
            arguments:
                - '6LflWQoUAAAAAGDlgrKTOPxxMXwpb932_Q_tuvKX'
            tags:
                - { name: form.type, alias: recaptcha}

    tbn.profile.form.type:
        class: TBN\UserBundle\Form\Type\ProfileFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: tbn_user_profile }

    authentication_handler:
        class: TBN\UserBundle\Handler\AuthenticationHandler
        arguments: ["@translator", "@router", "@session", "@site_manager"]
