imports:
    - { resource: config.yml }

fos_http_cache:
    proxy_client:
        default: varnish

framework:
    router:
        strict_requirements: false

monolog:
    use_microseconds: false
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: guillaume.sainthillier@gmail.com
            to_email:   guillaume.sainthillier@gmail.com
            subject:    Erreur sur By Night
            level:      critical
            formatter:    tbn.monolog_formatter
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
