imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@TBNMainBundle/Resources/config/services.yml" }

framework:
    esi: { enabled: true }
    translator:
        fallback:   %locale%
        logging:    false
    secret:         %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        hinclude_default_template: TBNAgendaBundle:Hinclude:template.html.twig
#        assets_version: v1
#        assets_version_format: %%2$s/%%1$s
    default_locale:  "%locale%"
    trusted_proxies: ~
    trusted_hosts:   ~
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       { path: /_fragment }
    http_method_override: true
    assets: ~
    
doctrine_cache:
    providers:
        memcache:
            type: file_system
            namespace: memory_cache_ns
            aliases:
                - memory_cache
        array:
            type: array
            namespace: array_cache_ns
            aliases:
                - array_cache
        
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form_themes:
            - 'VichUploaderBundle:Form:fields.html.twig'
            - ':Form:fields.html.twig'
    globals:
        menu: "@white_october_breadcrumbs"
        facebook_app_id: "%api_facebook_id%"
        twitter: "@tbn.social.twitter"
        facebook: "@tbn.social.facebook"
        google: "@tbn.social.google"
        googleMapKey: %google_map_key%

# Doctrine Configuration
doctrine:
    dbal:
        server_version: 5.7
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    port:      %mailer_port%
    sender_address: %mailer_user%
    spool:     { type: memory }

vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix:         /uploads/users
            upload_destination: %kernel.root_dir%/../web/uploads/users
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        event_image:
            uri_prefix:         /uploads/documents
            upload_destination: %kernel.root_dir%/../web/uploads/documents
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main  
    user_class: TBN\UserBundle\Entity\User
    profile:
        form:
            type: TBN\UserBundle\Form\Type\ProfileFormType
    
#ivory_google_map:
#    geocoder:
        # Enable the service
#        enabled: true

easy_admin:
    entities:
        - TBN\AgendaBundle\Entity\Agenda
        - TBN\UserBundle\Entity\User
        - TBN\MainBundle\Entity\Site
        - TBN\AgendaBundle\Entity\Place
        - TBN\AgendaBundle\Entity\Calendrier
        - TBN\CommentBundle\Entity\Comment
        - TBN\MajDataBundle\Entity\Exploration
        - TBN\MajDataBundle\Entity\HistoriqueMaj
        - TBN\UserBundle\Entity\SiteInfo
        - TBN\UserBundle\Entity\UserInfo

hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the 
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: my_user_provider
        confirmation: false
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    http_client:
        timeout:       10 # Time in seconds, after library will shutdown request, by default: 5
        verify_peer:   false # Setting allowing you to turn off SSL verification, by default: true
        ignore_errors: false # Setting allowing you to easier debug request errors, by default: true
        max_redirects: 1 # Number of HTTP redirection request after which library will shutdown request,
                         # by default: 5
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
            google: google_id
            twitter: twitter_id
    resource_owners:
        twitter:
            type:               twitter
            client_id:          %twitter_app_id%
            client_secret:      %twitter_app_secret%
        facebook_admin:
            type:                facebook
            client_id:           %api_facebook_id%
            client_secret:       %api_facebook_secret%
            scope:               email, publish_actions, manage_pages
            authorization_url:   https://www.facebook.com/v2.8/dialog/oauth
            infos_url:           https://graph.facebook.com/me?fields=name,email,picture.type(large)
            paths:
                email:          email
                profilepicture: picture.data.url
            options:
                display: popup #dialog is optimized for popup window
        facebook_events:
            type:                facebook
            client_id:           %api_facebook_id%
            client_secret:       %api_facebook_secret%
            scope:               email, user_posts
            authorization_url:   https://www.facebook.com/v2.8/dialog/oauth
            infos_url:           https://graph.facebook.com/me?fields=name,email,picture.type(large)
            paths:
                email:          email
                profilepicture: picture.data.url
            options:
                display: popup #dialog is optimized for popup window
        facebook:
            type:                facebook
            client_id:           %api_facebook_id%
            client_secret:       %api_facebook_secret%
            scope:               email, rsvp_event
            authorization_url:   https://www.facebook.com/v2.8/dialog/oauth
            infos_url:           https://graph.facebook.com/me?fields=name,email,picture.type(large)
            paths:
                email:          email
                profilepicture: picture.data.url
            options:
                display: popup #dialog is optimized for popup window
        google:
            type:                google
            client_id:           %google_app_id%
            client_secret:       %google_app_secret%
            scope:               https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.stream.read https://www.googleapis.com/auth/plus.stream.write
            options:
                access_type:         offline
                approval_prompt:     auto
                display:             popup
                login_hint:          email address

#be_simple_i18n_routing: ~

white_october_breadcrumbs: ~

liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        thumb_site_large:
            quality: 75
            filters:
                thumbnail: { size: [1970, 400], mode: outbound }
                interlace:
                    # mode can be one of none,line,plane,partition
                    mode: line
        thumb_site:
            quality: 100
            filters:
                relative_resize: { heighten: 350 }
        thumb_site:
            quality: 100
            filters:
                relative_resize: { heighten: 350 }
        thumbs_evenement:
            quality: 75
            filters:
#                relative_resize: { widen: 200 }
                relative_resize: { heighten: 200 }
#                thumbnail: { size: [200, 200], mode: outbound }
        thumb_evenement:
            quality: 100
            filters:
                relative_resize: { heighten: 250 }
#                thumbnail: { size: [250, 250], mode: outbound }
        thumb_user_evenement:
            quality: 75
            filters:
                relative_resize: { heighten: 128 }
#                thumbnail: { size: [128, 128], mode: outbound }
        thumb_user:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
        thumb_user_menu:
            quality: 75
            filters:
                thumbnail: { size: [30, 30], mode: outbound }
        thumb_user_50:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        thumb_user_115:
            quality: 75
            filters:
                thumbnail: { size: [115, 115], mode: outbound }

tbn_user:
    socials:
        facebook:
            enabled: true
            nom: Facebook
        twitter: 
            enabled: true
            nom: Twitter
        google: 
            enabled: false
            nom: Google+


fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    serializer: ~
    indexes:
        tbn:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_french_analyzer:
                                type: custom
                                tokenizer: nGram
                                filter: [stopwords, asciifolding, lowercase, snowball, elision, worddelimiter]
                            custom_search_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [stopwords, asciifolding, lowercase, snowball, elision, worddelimiter]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 2
                                max_gram: 20
                        filter:
                            snowball:
                                type:     snowball
                                language: French
                            elision:
                                type:     elision
                                articles: [l, m, t, qu, n, s, j, d]
                            stopwords:
                                type:      stop
                                stopwords: [_french_]
                                ignore_case : true
                            worddelimiter :
                                type:      word_delimiter
            types:
                event:
                    mappings:
                        nom: { boost: 5, analyzer: custom_french_analyzer, search_analyzer: custom_search_analyzer }
                        descriptif: { analyzer: custom_french_analyzer, search_analyzer: custom_search_analyzer }
                        dateDebut: { type: date, format: Y-m-d }
                        dateFin: { type: date, format: Y-m-d }
                        commune: ~
                        typeManifestation: ~
                        place:
                            type: "object"
                            properties:
                                nom: { boost: 3, analyzer: custom_french_analyzer, search_analyzer: custom_search_analyzer }
                                rue: { analyzer: custom_french_analyzer, search_analyzer: custom_search_analyzer }
                                codePostal: ~
                                ville: { boost: 2, analyzer: custom_french_analyzer, search_analyzer: custom_search_analyzer }
                        site:
                            type: "object"
                            properties:
                                id: ~                        
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model:  TBN\AgendaBundle\Entity\Agenda
                        repository: TBN\AgendaBundle\SearchRepository\AgendaRepository
                        provider: ~
                        listener: ~ # by default, listens to "insert", "update" and "delete"
                        finder: ~
                user:
                    mappings:
                        username: { boost: 5, analyzer: custom_french_analyzer, search_analyzer: custom_search_analyzer }
                        firstname: { boost: 1, analyzer: custom_french_analyzer, search_analyzer: custom_search_analyzer }
                        lastname: { boost: 1, analyzer: custom_french_analyzer, search_analyzer: custom_search_analyzer }
                        site:
                            type: "object"
                            properties:
                                id: ~
                    persistence:
                        driver: orm
                        model:  TBN\UserBundle\Entity\User
                        repository: TBN\UserBundle\SearchRepository\UserRepository
                        provider: ~
                        listener: ~ # by default, listens to "insert", "update" and "delete"
                        finder: ~

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "@TBNUserBundle/Resources/config/serializer/fos"

presta_sitemap:
    route_annotation_listener: false

lexik_maintenance:
    authorized:
        query: { debug: 1 }
    driver:
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'
        options: {file_path: "%kernel.cache_dir%/lock"}

services:
    fos_user.doctrine_registry:
        alias: doctrine
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

