imports:
    - { resource: config.yml }
    - { resource: config_dev.yml }

fos_http_cache:
    proxy_client:
        default: varnish

framework:
    router:
        resource: "%kernel.project_dir%/config/routing_dev.yml"
        strict_requirements: true
        http_port: 8081

