app.default:
    resource: "@AppBundle/Controller"
    type:     annotation

app.social:
    resource: "@AppBundle/Controller/Social"
    prefix:   /social
    type:     annotation

app.espace_perso:
    resource: "@AppBundle/Controller/EspacePerso"
    prefix:   /espace-perso
    type:     annotation

app.comments:
    resource: "@AppBundle/Controller/Comment"
    prefix:   /commentaire
    type:     annotation

app.legacy:
    resource: "@AppBundle/Controller/Legacy"
    type:     annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /_administration

app.admin:
    resource: "@AppBundle/Controller/Admin"
    prefix:   /_administration
    type:     annotation

app.search:
    resource: "@AppBundle/Controller/Search"
    prefix:   /recherche
    type:     annotation

app.private:
    resource: "@AppBundle/Controller/Fragments"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

#Login
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#Profile
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#Profile override
app_user_profile:
    resource: "@AppBundle/Controller/User/ProfileController.php"
    prefix: /profile
    type:     annotation

#app.user_profile:
#    resource: "@UserBundle/Controller"
#    prefix:   /profile

#Inscription
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

#Changement de password
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

#Demande de changement de password
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profil

#Login réseaux sociaux
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login-social

#Login réseaux sociaux
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login-social

#Login réseaux sociaux
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login-social

#Login réseaux sociaux override
app_hwi_oauth_connect:
    resource: "@AppBundle/Controller/Social/ConnectController.php"
    prefix: /login-social
    type:     annotation

#Login twitter
twitter_login:
    path: /login/check-twitter

#Login facebook
facebook_login:
    path: /login/check-facebook

#Login Google
google_login:
    path: /login/check-google

#La ville est définie à partir d'ici
app.city:
    resource: "@AppBundle/Controller/City"
    prefix:   /{city}
    type:     annotation

app.old:
    resource: "@AppBundle/Controller/Old"
    type:     annotation
