version: '2'

services:
    db:
        image: mysql:latest
        volumes:
            - db-data:/var/lib/mysql
            - ./mysql/app.cnf:/etc/mysql/conf.d/app.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
        networks:
            - backend
    redis:
        image: redis:alpine
        restart: always
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - db
        ports:
            - 8001:80
        volumes:
            - ./phpmyadmin/nginx.conf:/etc/nginx/conf.d/overrides.conf
            - ./phpmyadmin/php.conf:/etc/php7/conf.d/99-overrides.conf
        networks:
            - backend
        restart: always
    php:
        build: ./php-fpm
        links:
            - db:mysqldb
            - redis:redis
            - elk:elasticsearch
        depends_on:
            - db
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ../logs/symfony:/var/www/symfony/app/logs
        restart: always
        networks:
            - backend        
    nginx:
        build: nginx
        ports:
            - 8000:80
        links:
            - php
        volumes_from:
            - php
        depends_on:
            - db
            - php
            - redis
        volumes:
            - ../var/logs/nginx/:/var/log/nginx
        restart: always
        networks:
            - frontend
            - backend        
    elk:
        image: sebp/elk:latest
        ports:
            - 5602:5601
            - 9201:9200
            - 9301:9300
            - 5045:5044
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
            - ../var/logs:/var/www/symfony/var/logs
            - ../var/logs/nginx:/var/log/nginx
            - elk-data:/var/lib/elasticsearch
        networks:
            - backend
        restart: always
volumes:
    db-data:
        driver: local
    elk-data:
        driver: local

networks:
    frontend:
    backend: