parameters:
#    router.class: TBN\MainBundle\Routing\Router
#    tbn_city.example.class: TBN\CityBundle\Example
    #router.class: TBN\MainBundle\Routing\Router

    
services:
    tbn.profile_picture.event:
        class: TBN\MainBundle\Picture\EventProfilePicture
        arguments: [ "@liip_imagine.cache.manager", "@vich_uploader.templating.helper.uploader_helper", "@assets.packages"]

    tbn.profile_picture.user:
        class: TBN\MainBundle\Picture\UserProfilePicture
        arguments: [ "@liip_imagine.cache.manager", "@vich_uploader.templating.helper.uploader_helper" ]

    site_manager:
        class: TBN\MainBundle\Site\SiteManager
      
    ville_listener:
        class: TBN\MainBundle\Listener\SubDomainListener
        arguments: ["@site_manager", "@doctrine.orm.entity_manager", "@router", "%base_host%"]
        tags:
           - { name: kernel.event_listener, event: kernel.request, method: onDomainParse, priority: 100}

    image_listener:
        class: TBN\MainBundle\Listener\ImageListener
        arguments: ["@request_stack", "@liip_imagine.cache.manager"]
        tags:
           - { name: kernel.event_listener, event: "vich_uploader.pre_remove", method: onImageDelete}
           
    tbn.twig.main_extension:
        class: TBN\MainBundle\Twig\MainExtension
        arguments : ["@site_manager", "@service_container"]
        tags:
            - { name: twig.extension }
           
#Forms
    #Collections
    tbn.collections:
        class: TBN\MainBundle\Form\Extension\CollectionExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CollectionType }
    
    #Surcouche globale des formulaires
    tbn.forms:
        class: TBN\MainBundle\Form\Extension\WidgetFormTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
    #Datepicker
    tbn.forms.datepicker:
        class: TBN\MainBundle\Form\Extension\DateTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\DateType }
    #Image
    tbn.image_type_extension:
        class: TBN\MainBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Vich\UploaderBundle\Form\Type\VichImageType }
