tbn_disconnect_service_confirm:
    path: /confirmation/deconnexion/{service}
    defaults: { _controller: TBNSocialBundle:Social:disconnectConfirm}
    methods: [GET]
    requirements:
        service: (facebook|google|twitter)        

tbn_disconnect_service:
    path: /deconnexion/{service}
    defaults: { _controller: TBNSocialBundle:Social:disconnect}
    methods: [POST]
    requirements:
        service: (facebook|google|twitter)
