tbn_disconnect_service_confirm:
    pattern: /confirmation/deconnexion/{service}
    defaults: { _controller: TBNSocialBundle:Social:disconnectConfirm}
    requirements:
        service: (facebook|google|twitter)
        _method: GET

tbn_disconnect_service:
    pattern: /deconnexion/{service}
    defaults: { _controller: TBNSocialBundle:Social:disconnect}
    requirements:
        service: (facebook|google|twitter)
        _method: POST
