app.default:
    resource: "../src/Controller/"
    type:     annotation

app.social:
    resource: "../src/Controller/Social"
    prefix:   /social
    type:     annotation

app.espace_perso:
    resource: "../src/Controller/EspacePerso"
    prefix:   /espace-perso
    type:     annotation

app.comments:
    resource: "../src/Controller/Comment"
    prefix:   /commentaire
    type:     annotation

app.legacy:
    resource: "../src/Controller/Legacy"
    type:     annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /_administration

app.admin:
    resource: "../src/Controller/Admin"
    prefix:   /_administration
    type:     annotation

app.search:
    resource: "../src/Controller/Search"
    prefix:   /recherche
    type:     annotation

app.private:
    resource: "../src/Controller/Fragments"

#Login
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#Profile
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#Profile override
app_user_profile:
    resource: "../src/Controller/User/ProfileController.php"
    prefix: /profile
    type:     annotation

#Inscription
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

#Changement de password
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

#Demande de changement de password
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profil

#Login réseaux sociaux
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login_41.xml"
    prefix: /login-social

#Login réseaux sociaux
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect_41.xml"
    prefix: /login-social

#Login réseaux sociaux
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect_41.xml"
    prefix:   /login-social

#Login réseaux sociaux override
app_hwi_oauth_connect:
    resource: "../src/Controller/Social/ConnectController.php"
    prefix: /login-social
    type:     annotation

#Login twitter
twitter_login:
    path: /login/check-twitter

#Login facebook
facebook_login:
    path: /login/check-facebook

#Login Google
google_login:
    path: /login/check-google

#Login Eventbrite
eventbrite_login:
    path: /login/check-eventbrite

#La ville est définie à partir d'ici
app.city:
    resource: "../src/Controller/City"
    prefix:   /{location}
    type:     annotation
