tbn_agenda_index:
    path: /
    defaults: { _controller: TBNAgendaBundle:Event:index}
    
tbn_agenda_agenda:
    path: /agenda
    defaults: { _controller: TBNAgendaBundle:Event:list, page: 1}

tbn_agenda_pagination:
    path: /agenda/page/{page}
    defaults: { _controller: TBNAgendaBundle:Event:list}
    methods: [GET]
    requirements:
        page: \d+
        
tbn_agenda_mention_legales:
    path: /mentions-legales.html
    methods: [GET]
    defaults: { _controller: TBNAgendaBundle:Legacy:mentionLegales}

tbn_agenda_about:
    path: /a-propos.html
    methods: [GET]
    defaults: { _controller: TBNAgendaBundle:Legacy:about}

tbn_agenda_plus:
    path: /en-savoir-plus.html
    methods: [GET]
    defaults: { _controller: TBNAgendaBundle:Legacy:plus}

tbn_agenda_top_soirees:
    path: /top/soirees
    defaults: { _controller: TBNAgendaBundle:MenuDroit:topSoirees}

tbn_agenda_programme_tv: 
    path: /programme-tv
    methods: [GET]
    defaults: { _controller: TBNAgendaBundle:MenuDroit:programmeTV}
    
tbn_agenda_top_membres:
    path: /top/membres
    defaults: { _controller: TBNAgendaBundle:MenuDroit:topMembres}

tbn_agenda_details:
    path: /soiree/{slug}.html
    defaults: { _controller: TBNAgendaBundle:Event:details}
    requirements:
        slug: (.+)

tbn_agenda_soirees_similaires:
    path: /soiree/{slug}.html/autres-soirees/{page}
    defaults: { _controller: TBNAgendaBundle:MenuDroit:soireesSimilaires, page: 1}
    requirements:
        page: (\d+)

tbn_agenda_soirees_tendances:
    path: /soiree/{slug}.html/tendances
    defaults: { _controller: TBNAgendaBundle:MenuDroit:tendances}
    
tbn_agenda_soirees_membres:
    path: /soiree/{slug}.html/membres/{page}
    defaults: { _controller: TBNAgendaBundle:MenuDroit:fbMembres, page: 1}
    requirements:
        page: (\d+)
