tbn_agenda_index:
    path: /
    defaults: { _controller: TBNAgendaBundle:Event:index}
    
tbn_agenda_agenda:
    path: /agenda
    defaults: { _controller: TBNAgendaBundle:Event:list, page: 1, type: null, tag: null, ville: null, slug: null}
    
tbn_agenda_sortir:
    path: /agenda/sortir/{type}
    defaults: { _controller: TBNAgendaBundle:Event:list, page: 1, tag: null, ville: null, slug: null, paginateRoute: "tbn_agenda_sortir_pagination"}
    requirements:
        type: concert|spectacle|etudiant|famille|exposition

tbn_agenda_sortir_pagination:
    path: /agenda/sortir/{type}/page/{page}
    defaults: { _controller: TBNAgendaBundle:Event:list, page: 1, tag: null, ville: null, slug: null, paginateRoute: "tbn_agenda_sortir_pagination"}
    requirements:
        type: concert|spectacle|etudiant|famille|exposition
        page: \d+

tbn_agenda_tags_pagination:
    path: /agenda/tag/{tag}/page/{page}
    defaults: { _controller: TBNAgendaBundle:Event:list, page: 1, type: null, ville: null, slug: null, paginateRoute: "tbn_agenda_tags_pagination"}
    requirements:
        tag: (.+)
        page: (\d+)

tbn_agenda_tags:
    path: /agenda/tag/{tag}
    defaults: { _controller: TBNAgendaBundle:Event:list, page: 1, type: null, ville: null, slug: null, paginateRoute: "tbn_agenda_tags_pagination"}
    requirements:
        tag: (.+)

tbn_agenda_place_pagination:
    path: /agenda/sortir-a/{slug}/page/{page}
    defaults: { _controller: TBNAgendaBundle:Event:list, page: 1, type: null, ville: null, tag: null, paginateRoute: "tbn_agenda_place_pagination"}
    requirements:
        tag: (.+)
        page: (\d+)

tbn_agenda_place:
    path: /agenda/sortir-a/{slug}
    defaults: { _controller: TBNAgendaBundle:Event:list, page: 1, type: null, ville: null, tag: null, paginateRoute: "tbn_agenda_place_pagination"}
    requirements:
        tag: (.+)
        
tbn_agenda_ville_pagination:
    path: /agenda/sortir-dans/{ville}/page/{page}
    defaults: { _controller: TBNAgendaBundle:Event:list, page: 1, type: null, slug: null, tag: null, paginateRoute: "tbn_agenda_ville_pagination"}
    requirements:
        tag: (.+)
        page: (\d+)

tbn_agenda_ville:
    path: /agenda/sortir-dans/{ville}
    defaults: { _controller: TBNAgendaBundle:Event:list, page: 1, type: null, slug: null, tag: null, paginateRoute: "tbn_agenda_ville_pagination"}
    requirements:
        tag: (.+)

tbn_agenda_pagination:
    path: /agenda/page/{page}
    defaults: { _controller: TBNAgendaBundle:Event:list, page: 1, type: null, tag: null, ville: null, slug: null}
    methods: [GET]
    requirements:
        page: (\d+)
        
tbn_agenda_mention_legales:
    path: /mentions-legales.html
    methods: [GET]
    defaults: { _controller: TBNAgendaBundle:Legacy:mentionLegales}

tbn_agenda_about:
    path: /a-propos.html
    methods: [GET]
    defaults: { _controller: TBNAgendaBundle:Legacy:about}

tbn_agenda_plus:
    path: /en-savoir-plus.html
    methods: [GET]
    defaults: { _controller: TBNAgendaBundle:Legacy:plus}

tbn_agenda_top_soirees:
    path: /top/soirees/{page}
    defaults: { _controller: TBNAgendaBundle:MenuDroit:topSoirees}
    requirements:
        page: (\d+)

tbn_agenda_programme_tv: 
    path: /programme-tv
    methods: [GET]
    defaults: { _controller: TBNAgendaBundle:MenuDroit:programmeTV}

tbn_agenda_tweeter_feed:
    path: /tweeter-feed/{max_id}
    methods: [GET]
    defaults: { _controller: TBNAgendaBundle:MenuDroit:twitter, max_id: null}
    requirements:
        max_id: (\d+)
    
tbn_agenda_top_membres:
    path: /top/membres/{page}
    defaults: { _controller: TBNAgendaBundle:MenuDroit:topMembres}
    requirements:
        page: (\d+)

tbn_agenda_details:
    path: /soiree/{slug}.html
    defaults: { _controller: TBNAgendaBundle:Event:details}
    requirements:
        slug: (.+)

tbn_agenda_prochaines_soirees:
    path: /soiree/{slug}.html/prochaines-soirees/{page}
    defaults: { _controller: TBNAgendaBundle:MenuDroit:nextEvents, page: 1}
    requirements:
        slug: (.+)

tbn_agenda_soirees_similaires:
    path: /soiree/{slug}.html/autres-soirees/{page}
    defaults: { _controller: TBNAgendaBundle:MenuDroit:soireesSimilaires, page: 1}
    requirements:
        page: (\d+)
    
tbn_agenda_soirees_membres:
    path: /soiree/{slug}.html/membres/{page}
    defaults: { _controller: TBNAgendaBundle:MenuDroit:fbMembres, page: 1}
    requirements:
        page: (\d+)
